services:
  jackett:
      container_name: jackett
      image: linuxserver/jackett
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=Europe/Lisbon
      volumes:
        - '/home/ampc/apps/jackett/config:/config'
        - '/home/ampc/downloads/torrents:/downloads'
      ports:
        - '9117:9117'
      restart: unless-stopped
  radarr:
      container_name: radarr
      image: linuxserver/radarr
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=Europe/Lisbon
      ports:
        - '7878:7878'
      volumes:
        - '/home/ampc/apps/radarr/config:/config'
        - '/home/ampc/server/data:/data'
      restart: unless-stopped
  sonarr:
      container_name: sonarr
      image: linuxserver/sonarr
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=Europe/Lisbon
      ports:
        - '8989:8989'
      volumes:
        - '/home/ampc/apps/sonarr/config:/config'
        - '/home/ampc/server/data:/data'
      restart: unless-stopped
  jellyseerr:
      image: fallenbagel/jellyseerr:latest
      container_name: jellyseerr
      environment:
        - LOG_LEVEL=debug
        - TZ=Europe/Lisbon
        - PUID=1000
        - PGID=1000
      ports:
        - '5055:5055'
      volumes:
        - '/home/ampc/apps/jellyseerr/config:/app/config'
      restart: unless-stopped